SUPPORTED_LANGUAGES = {
    "de-DE": "German (Germany)",
    "en-AU": "English (Australia)",
    "en-GB": "English (United Kingdom)",
    "en-IN": "English (India)",
    "en-US": "English (US)",
    "es-US": "Spanish (United States)",
    "fr-FR": "French (France)",
    "hi-IN": "Hindi (India)",
    "pt-BR": "Portuguese (Brazil)",
    "ar-XA": "Arabic (Generic)",
    "es-ES": "Spanish (Spain)",
    "fr-CA": "French (Canada)",
    "id-ID": "Indonesian (Indonesia)",
    "it-IT": "Italian (Italy)",
    "ja-JP": "Japanese (Japan)",
    "tr-TR": "Turkish (Turkey)",
    "vi-VN": "Vietnamese (Vietnam)",
    "bn-IN": "Bengali (India)",
    "gu-IN": "Gujarati (India)",
    "kn-IN": "Kannada (India)",
    "ml-IN": "Malayalam (India)",
    "mr-IN": "Marathi (India)",
    "ta-IN": "Tamil (India)",
    "te-IN": "Telugu (India)",
    "nl-NL": "Dutch (Netherlands)",
    "ko-KR": "Korean (South Korea)",
    "cmn-CN": "Mandarin Chinese (China)",
    "pl-PL": "Polish (Poland)",
    "ru-RU": "Russian (Russia)",
    "th-TH": "Thai (Thailand)",
}
